// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// How the microphone is gated.
enum TalkMode {
  pushToTalk,
  continuous,
}

/// Message priority. `alert` is spoken at max volume and cannot be muted.
enum Priority {
  normal,
  alert,
}

enum PackKind {
  stt,
  tts,
  vad,
}

/// Which radio carried the packet.
enum LinkKind {
  ble,
  wifiDirect,
  local,
}

class ModelPackInfo {
  ModelPackInfo({
    required this.lang,
    required this.kind,
    required this.engine,
    required this.installed,
    required this.sizeBytes,
    required this.version,
    required this.path,
  });

  String lang;

  PackKind kind;

  String engine;

  bool installed;

  int sizeBytes;

  String version;

  String path;

  Object encode() {
    return <Object?>[
      lang,
      kind,
      engine,
      installed,
      sizeBytes,
      version,
      path,
    ];
  }

  static ModelPackInfo decode(Object result) {
    result as List<Object?>;
    return ModelPackInfo(
      lang: result[0]! as String,
      kind: result[1]! as PackKind,
      engine: result[2]! as String,
      installed: result[3]! as bool,
      sizeBytes: result[4]! as int,
      version: result[5]! as String,
      path: result[6]! as String,
    );
  }
}

class PeerInfo {
  PeerInfo({
    required this.peerId,
    required this.nickname,
    required this.lang,
    required this.rssi,
    required this.hops,
    required this.link,
    required this.lastSeenMs,
  });

  String peerId;

  String nickname;

  String lang;

  int rssi;

  int hops;

  LinkKind link;

  int lastSeenMs;

  Object encode() {
    return <Object?>[
      peerId,
      nickname,
      lang,
      rssi,
      hops,
      link,
      lastSeenMs,
    ];
  }

  static PeerInfo decode(Object result) {
    result as List<Object?>;
    return PeerInfo(
      peerId: result[0]! as String,
      nickname: result[1]! as String,
      lang: result[2]! as String,
      rssi: result[3]! as int,
      hops: result[4]! as int,
      link: result[5]! as LinkKind,
      lastSeenMs: result[6]! as int,
    );
  }
}

class IncomingMessage {
  IncomingMessage({
    required this.id,
    required this.senderId,
    required this.senderNick,
    required this.lang,
    required this.text,
    required this.priority,
    required this.sentAtMs,
    required this.receivedAtMs,
    required this.hops,
    required this.link,
    required this.bytesOnWire,
  });

  String id;

  String senderId;

  String senderNick;

  String lang;

  String text;

  Priority priority;

  int sentAtMs;

  int receivedAtMs;

  int hops;

  LinkKind link;

  int bytesOnWire;

  Object encode() {
    return <Object?>[
      id,
      senderId,
      senderNick,
      lang,
      text,
      priority,
      sentAtMs,
      receivedAtMs,
      hops,
      link,
      bytesOnWire,
    ];
  }

  static IncomingMessage decode(Object result) {
    result as List<Object?>;
    return IncomingMessage(
      id: result[0]! as String,
      senderId: result[1]! as String,
      senderNick: result[2]! as String,
      lang: result[3]! as String,
      text: result[4]! as String,
      priority: result[5]! as Priority,
      sentAtMs: result[6]! as int,
      receivedAtMs: result[7]! as int,
      hops: result[8]! as int,
      link: result[9]! as LinkKind,
      bytesOnWire: result[10]! as int,
    );
  }
}

class TranscriptEvent {
  TranscriptEvent({
    required this.text,
    required this.isFinal,
    required this.lang,
    required this.utteranceMs,
    required this.decodeMs,
  });

  String text;

  bool isFinal;

  String lang;

  int utteranceMs;

  int decodeMs;

  Object encode() {
    return <Object?>[
      text,
      isFinal,
      lang,
      utteranceMs,
      decodeMs,
    ];
  }

  static TranscriptEvent decode(Object result) {
    result as List<Object?>;
    return TranscriptEvent(
      text: result[0]! as String,
      isFinal: result[1]! as bool,
      lang: result[2]! as String,
      utteranceMs: result[3]! as int,
      decodeMs: result[4]! as int,
    );
  }
}

class Diagnostics {
  Diagnostics({
    required this.sttLoaded,
    required this.ttsLoaded,
    required this.sttRtf,
    required this.ttsRtf,
    required this.nativeHeapMb,
    required this.packetsSent,
    required this.packetsReceived,
    required this.packetsRelayed,
    required this.bytesSent,
    required this.bytesReceived,
    required this.blePeers,
    required this.wifiPeers,
    required this.lastE2eLatencyMs,
  });

  String sttLoaded;

  String ttsLoaded;

  double sttRtf;

  double ttsRtf;

  double nativeHeapMb;

  int packetsSent;

  int packetsReceived;

  int packetsRelayed;

  int bytesSent;

  int bytesReceived;

  int blePeers;

  int wifiPeers;

  int lastE2eLatencyMs;

  Object encode() {
    return <Object?>[
      sttLoaded,
      ttsLoaded,
      sttRtf,
      ttsRtf,
      nativeHeapMb,
      packetsSent,
      packetsReceived,
      packetsRelayed,
      bytesSent,
      bytesReceived,
      blePeers,
      wifiPeers,
      lastE2eLatencyMs,
    ];
  }

  static Diagnostics decode(Object result) {
    result as List<Object?>;
    return Diagnostics(
      sttLoaded: result[0]! as String,
      ttsLoaded: result[1]! as String,
      sttRtf: result[2]! as double,
      ttsRtf: result[3]! as double,
      nativeHeapMb: result[4]! as double,
      packetsSent: result[5]! as int,
      packetsReceived: result[6]! as int,
      packetsRelayed: result[7]! as int,
      bytesSent: result[8]! as int,
      bytesReceived: result[9]! as int,
      blePeers: result[10]! as int,
      wifiPeers: result[11]! as int,
      lastE2eLatencyMs: result[12]! as int,
    );
  }
}

class Identity {
  Identity({
    required this.peerId,
    required this.nickname,
    required this.lang,
  });

  String peerId;

  String nickname;

  String lang;

  Object encode() {
    return <Object?>[
      peerId,
      nickname,
      lang,
    ];
  }

  static Identity decode(Object result) {
    result as List<Object?>;
    return Identity(
      peerId: result[0]! as String,
      nickname: result[1]! as String,
      lang: result[2]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TalkMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is Priority) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PackKind) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is LinkKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is ModelPackInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PeerInfo) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is IncomingMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is TranscriptEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is Diagnostics) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is Identity) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TalkMode.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : Priority.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PackKind.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : LinkKind.values[value];
      case 133: 
        return ModelPackInfo.decode(readValue(buffer)!);
      case 134: 
        return PeerInfo.decode(readValue(buffer)!);
      case 135: 
        return IncomingMessage.decode(readValue(buffer)!);
      case 136: 
        return TranscriptEvent.decode(readValue(buffer)!);
      case 137: 
        return Diagnostics.decode(readValue(buffer)!);
      case 138: 
        return Identity.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SpeechApi {
  /// Constructor for [SpeechApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SpeechApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Loads STT for [lang] (unloading any other). Blocking, ~1-3 s.
  Future<void> loadStt(String lang) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.loadStt$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[lang]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Ensures a TTS voice for [lang] is resident.
  Future<void> loadTts(String lang) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.loadTts$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[lang]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setTalkMode(TalkMode mode) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.setTalkMode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mode]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start capturing. In PTT mode the caller holds and releases.
  Future<void> startCapture() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.startCapture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stop capturing and flush any pending utterance through STT.
  Future<void> stopCapture() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.stopCapture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Speak locally (used for previews and the receive path fallback).
  Future<void> speak(String text, String lang, Priority priority) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.speak$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[text, lang, priority]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopSpeaking() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.stopSpeaking$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Send text that was typed rather than spoken.
  Future<void> sendText(String text, Priority priority) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.sendText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[text, priority]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isSpeaking() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.SpeechApi.isSpeaking$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

class MeshApi {
  /// Constructor for [MeshApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MeshApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<Identity> getIdentity() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.getIdentity$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Identity?)!;
    }
  }

  Future<void> setNickname(String nickname) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.setNickname$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nickname]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setLanguage(String lang) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.setLanguage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[lang]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> start() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stop() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isRunning() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.isRunning$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<List<PeerInfo>> peers() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.peers$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<PeerInfo>();
    }
  }

  Future<Diagnostics> diagnostics() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.diagnostics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Diagnostics?)!;
    }
  }

  /// Acknowledge (silence) the currently playing alert.
  Future<void> acknowledgeAlert() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.MeshApi.acknowledgeAlert$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

class ModelApi {
  /// Constructor for [ModelApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ModelApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<ModelPackInfo>> listPacks() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.ModelApi.listPacks$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ModelPackInfo>();
    }
  }

  /// Import a `.itpack` zip from a content:// or file path. Returns the manifest.
  Future<ModelPackInfo> importPack(String uriOrPath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.ModelApi.importPack$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[uriOrPath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ModelPackInfo?)!;
    }
  }

  Future<void> deletePack(String lang, PackKind kind) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.ModelApi.deletePack$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[lang, kind]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Download `<lang>-<kind>.itpack` from the published packs and install it.
  /// Progress arrives via EventsApi.onPackProgress(lang, kind, 0..1).
  Future<ModelPackInfo> downloadPack(String lang, PackKind kind) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.ModelApi.downloadPack$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[lang, kind]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ModelPackInfo?)!;
    }
  }

  Future<void> cancelDownload(String lang, PackKind kind) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.ModelApi.cancelDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[lang, kind]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Directory where packs live, for the file picker hint.
  Future<String> packsDir() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.itantra.ModelApi.packsDir$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }
}

abstract class EventsApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onTranscript(TranscriptEvent event);

  void onMessage(IncomingMessage message);

  void onPeersChanged(List<PeerInfo> peers);

  void onSpeakingChanged(bool speaking, String messageId);

  void onAlertState(bool active, String messageId);

  void onCaptureLevel(double rms);

  void onError(String code, String message);

  void onPackProgress(String lang, PackKind kind, double progress);

  static void setUp(EventsApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onTranscript$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onTranscript was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TranscriptEvent? arg_event = (args[0] as TranscriptEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onTranscript was null, expected non-null TranscriptEvent.');
          try {
            api.onTranscript(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final IncomingMessage? arg_message = (args[0] as IncomingMessage?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onMessage was null, expected non-null IncomingMessage.');
          try {
            api.onMessage(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onPeersChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onPeersChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<PeerInfo>? arg_peers = (args[0] as List<Object?>?)?.cast<PeerInfo>();
          assert(arg_peers != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onPeersChanged was null, expected non-null List<PeerInfo>.');
          try {
            api.onPeersChanged(arg_peers!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onSpeakingChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onSpeakingChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_speaking = (args[0] as bool?);
          assert(arg_speaking != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onSpeakingChanged was null, expected non-null bool.');
          final String? arg_messageId = (args[1] as String?);
          assert(arg_messageId != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onSpeakingChanged was null, expected non-null String.');
          try {
            api.onSpeakingChanged(arg_speaking!, arg_messageId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onAlertState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onAlertState was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_active = (args[0] as bool?);
          assert(arg_active != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onAlertState was null, expected non-null bool.');
          final String? arg_messageId = (args[1] as String?);
          assert(arg_messageId != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onAlertState was null, expected non-null String.');
          try {
            api.onAlertState(arg_active!, arg_messageId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onCaptureLevel$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onCaptureLevel was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_rms = (args[0] as double?);
          assert(arg_rms != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onCaptureLevel was null, expected non-null double.');
          try {
            api.onCaptureLevel(arg_rms!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_code = (args[0] as String?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onError was null, expected non-null String.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.itantra.EventsApi.onPackProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.itantra.EventsApi.onPackProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_lang = (args[0] as String?);
          assert(arg_lang != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onPackProgress was null, expected non-null String.');
          final PackKind? arg_kind = (args[1] as PackKind?);
          assert(arg_kind != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onPackProgress was null, expected non-null PackKind.');
          final double? arg_progress = (args[2] as double?);
          assert(arg_progress != null,
              'Argument for dev.flutter.pigeon.itantra.EventsApi.onPackProgress was null, expected non-null double.');
          try {
            api.onPackProgress(arg_lang!, arg_kind!, arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
