// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package itantra.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** How the microphone is gated. */
enum class TalkMode(val raw: Int) {
  PUSH_TO_TALK(0),
  CONTINUOUS(1);

  companion object {
    fun ofRaw(raw: Int): TalkMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Message priority. `alert` is spoken at max volume and cannot be muted. */
enum class Priority(val raw: Int) {
  NORMAL(0),
  ALERT(1);

  companion object {
    fun ofRaw(raw: Int): Priority? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PackKind(val raw: Int) {
  STT(0),
  TTS(1),
  VAD(2);

  companion object {
    fun ofRaw(raw: Int): PackKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Which radio carried the packet. */
enum class LinkKind(val raw: Int) {
  BLE(0),
  WIFI_DIRECT(1),
  LOCAL(2);

  companion object {
    fun ofRaw(raw: Int): LinkKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModelPackInfo (
  val lang: String,
  val kind: PackKind,
  val engine: String,
  val installed: Boolean,
  val sizeBytes: Long,
  val version: String,
  val path: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelPackInfo {
      val lang = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as PackKind
      val engine = pigeonVar_list[2] as String
      val installed = pigeonVar_list[3] as Boolean
      val sizeBytes = pigeonVar_list[4] as Long
      val version = pigeonVar_list[5] as String
      val path = pigeonVar_list[6] as String
      return ModelPackInfo(lang, kind, engine, installed, sizeBytes, version, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lang,
      kind,
      engine,
      installed,
      sizeBytes,
      version,
      path,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeerInfo (
  val peerId: String,
  val nickname: String,
  val lang: String,
  val rssi: Long,
  val hops: Long,
  val link: LinkKind,
  val lastSeenMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeerInfo {
      val peerId = pigeonVar_list[0] as String
      val nickname = pigeonVar_list[1] as String
      val lang = pigeonVar_list[2] as String
      val rssi = pigeonVar_list[3] as Long
      val hops = pigeonVar_list[4] as Long
      val link = pigeonVar_list[5] as LinkKind
      val lastSeenMs = pigeonVar_list[6] as Long
      return PeerInfo(peerId, nickname, lang, rssi, hops, link, lastSeenMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peerId,
      nickname,
      lang,
      rssi,
      hops,
      link,
      lastSeenMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IncomingMessage (
  val id: String,
  val senderId: String,
  val senderNick: String,
  val lang: String,
  val text: String,
  val priority: Priority,
  val sentAtMs: Long,
  val receivedAtMs: Long,
  val hops: Long,
  val link: LinkKind,
  val bytesOnWire: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IncomingMessage {
      val id = pigeonVar_list[0] as String
      val senderId = pigeonVar_list[1] as String
      val senderNick = pigeonVar_list[2] as String
      val lang = pigeonVar_list[3] as String
      val text = pigeonVar_list[4] as String
      val priority = pigeonVar_list[5] as Priority
      val sentAtMs = pigeonVar_list[6] as Long
      val receivedAtMs = pigeonVar_list[7] as Long
      val hops = pigeonVar_list[8] as Long
      val link = pigeonVar_list[9] as LinkKind
      val bytesOnWire = pigeonVar_list[10] as Long
      return IncomingMessage(id, senderId, senderNick, lang, text, priority, sentAtMs, receivedAtMs, hops, link, bytesOnWire)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      senderId,
      senderNick,
      lang,
      text,
      priority,
      sentAtMs,
      receivedAtMs,
      hops,
      link,
      bytesOnWire,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TranscriptEvent (
  val text: String,
  val isFinal: Boolean,
  val lang: String,
  val utteranceMs: Long,
  val decodeMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TranscriptEvent {
      val text = pigeonVar_list[0] as String
      val isFinal = pigeonVar_list[1] as Boolean
      val lang = pigeonVar_list[2] as String
      val utteranceMs = pigeonVar_list[3] as Long
      val decodeMs = pigeonVar_list[4] as Long
      return TranscriptEvent(text, isFinal, lang, utteranceMs, decodeMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      isFinal,
      lang,
      utteranceMs,
      decodeMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Diagnostics (
  val sttLoaded: String,
  val ttsLoaded: String,
  val sttRtf: Double,
  val ttsRtf: Double,
  val nativeHeapMb: Double,
  val packetsSent: Long,
  val packetsReceived: Long,
  val packetsRelayed: Long,
  val bytesSent: Long,
  val bytesReceived: Long,
  val blePeers: Long,
  val wifiPeers: Long,
  val lastE2eLatencyMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Diagnostics {
      val sttLoaded = pigeonVar_list[0] as String
      val ttsLoaded = pigeonVar_list[1] as String
      val sttRtf = pigeonVar_list[2] as Double
      val ttsRtf = pigeonVar_list[3] as Double
      val nativeHeapMb = pigeonVar_list[4] as Double
      val packetsSent = pigeonVar_list[5] as Long
      val packetsReceived = pigeonVar_list[6] as Long
      val packetsRelayed = pigeonVar_list[7] as Long
      val bytesSent = pigeonVar_list[8] as Long
      val bytesReceived = pigeonVar_list[9] as Long
      val blePeers = pigeonVar_list[10] as Long
      val wifiPeers = pigeonVar_list[11] as Long
      val lastE2eLatencyMs = pigeonVar_list[12] as Long
      return Diagnostics(sttLoaded, ttsLoaded, sttRtf, ttsRtf, nativeHeapMb, packetsSent, packetsReceived, packetsRelayed, bytesSent, bytesReceived, blePeers, wifiPeers, lastE2eLatencyMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sttLoaded,
      ttsLoaded,
      sttRtf,
      ttsRtf,
      nativeHeapMb,
      packetsSent,
      packetsReceived,
      packetsRelayed,
      bytesSent,
      bytesReceived,
      blePeers,
      wifiPeers,
      lastE2eLatencyMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Identity (
  val peerId: String,
  val nickname: String,
  val lang: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Identity {
      val peerId = pigeonVar_list[0] as String
      val nickname = pigeonVar_list[1] as String
      val lang = pigeonVar_list[2] as String
      return Identity(peerId, nickname, lang)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peerId,
      nickname,
      lang,
    )
  }
}
private open class ItantraApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TalkMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Priority.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PackKind.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LinkKind.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelPackInfo.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeerInfo.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IncomingMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TranscriptEvent.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Diagnostics.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Identity.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TalkMode -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is Priority -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is PackKind -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is LinkKind -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is ModelPackInfo -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PeerInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is IncomingMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is TranscriptEvent -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is Diagnostics -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is Identity -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SpeechApi {
  /** Loads STT for [lang] (unloading any other). Blocking, ~1-3 s. */
  fun loadStt(lang: String, callback: (Result<Unit>) -> Unit)
  /** Ensures a TTS voice for [lang] is resident. */
  fun loadTts(lang: String, callback: (Result<Unit>) -> Unit)
  fun setTalkMode(mode: TalkMode)
  /** Start capturing. In PTT mode the caller holds and releases. */
  fun startCapture()
  /** Stop capturing and flush any pending utterance through STT. */
  fun stopCapture()
  /** Speak locally (used for previews and the receive path fallback). */
  fun speak(text: String, lang: String, priority: Priority, callback: (Result<Unit>) -> Unit)
  fun stopSpeaking()
  /** Send text that was typed rather than spoken. */
  fun sendText(text: String, priority: Priority)
  fun isSpeaking(): Boolean

  companion object {
    /** The codec used by SpeechApi. */
    val codec: MessageCodec<Any?> by lazy {
      ItantraApiPigeonCodec()
    }
    /** Sets up an instance of `SpeechApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SpeechApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.loadStt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val langArg = args[0] as String
            api.loadStt(langArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.loadTts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val langArg = args[0] as String
            api.loadTts(langArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.setTalkMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as TalkMode
            val wrapped: List<Any?> = try {
              api.setTalkMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.startCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startCapture()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.stopCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopCapture()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.speak$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val langArg = args[1] as String
            val priorityArg = args[2] as Priority
            api.speak(textArg, langArg, priorityArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.stopSpeaking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopSpeaking()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.sendText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val priorityArg = args[1] as Priority
            val wrapped: List<Any?> = try {
              api.sendText(textArg, priorityArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.SpeechApi.isSpeaking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSpeaking())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeshApi {
  fun getIdentity(): Identity
  fun setNickname(nickname: String)
  fun setLanguage(lang: String)
  fun start()
  fun stop()
  fun isRunning(): Boolean
  fun peers(): List<PeerInfo>
  fun diagnostics(): Diagnostics
  /** Acknowledge (silence) the currently playing alert. */
  fun acknowledgeAlert()

  companion object {
    /** The codec used by MeshApi. */
    val codec: MessageCodec<Any?> by lazy {
      ItantraApiPigeonCodec()
    }
    /** Sets up an instance of `MeshApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeshApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.getIdentity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getIdentity())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.setNickname$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nicknameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setNickname(nicknameArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.setLanguage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val langArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setLanguage(langArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.start()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.isRunning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isRunning())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.peers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.peers())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.diagnostics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.diagnostics())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.MeshApi.acknowledgeAlert$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.acknowledgeAlert()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ModelApi {
  fun listPacks(): List<ModelPackInfo>
  /** Import a `.itpack` zip from a content:// or file path. Returns the manifest. */
  fun importPack(uriOrPath: String, callback: (Result<ModelPackInfo>) -> Unit)
  fun deletePack(lang: String, kind: PackKind)
  /**
   * Download `<lang>-<kind>.itpack` from the published packs and install it.
   * Progress arrives via EventsApi.onPackProgress(lang, kind, 0..1).
   */
  fun downloadPack(lang: String, kind: PackKind, callback: (Result<ModelPackInfo>) -> Unit)
  fun cancelDownload(lang: String, kind: PackKind)
  /** Directory where packs live, for the file picker hint. */
  fun packsDir(): String

  companion object {
    /** The codec used by ModelApi. */
    val codec: MessageCodec<Any?> by lazy {
      ItantraApiPigeonCodec()
    }
    /** Sets up an instance of `ModelApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ModelApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.ModelApi.listPacks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listPacks())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.ModelApi.importPack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriOrPathArg = args[0] as String
            api.importPack(uriOrPathArg) { result: Result<ModelPackInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.ModelApi.deletePack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val langArg = args[0] as String
            val kindArg = args[1] as PackKind
            val wrapped: List<Any?> = try {
              api.deletePack(langArg, kindArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.ModelApi.downloadPack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val langArg = args[0] as String
            val kindArg = args[1] as PackKind
            api.downloadPack(langArg, kindArg) { result: Result<ModelPackInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.ModelApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val langArg = args[0] as String
            val kindArg = args[1] as PackKind
            val wrapped: List<Any?> = try {
              api.cancelDownload(langArg, kindArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.itantra.ModelApi.packsDir$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.packsDir())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class EventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      ItantraApiPigeonCodec()
    }
  }
  fun onTranscript(eventArg: TranscriptEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onTranscript$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onMessage(messageArg: IncomingMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onMessage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPeersChanged(peersArg: List<PeerInfo>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onPeersChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peersArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSpeakingChanged(speakingArg: Boolean, messageIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onSpeakingChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(speakingArg, messageIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onAlertState(activeArg: Boolean, messageIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onAlertState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(activeArg, messageIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onCaptureLevel(rmsArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onCaptureLevel$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(rmsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPackProgress(langArg: String, kindArg: PackKind, progressArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.itantra.EventsApi.onPackProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(langArg, kindArg, progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
